namespace QA.TelerikAcademy.Core.Constants.Pages
{
    public class AboutConstants
    {
        public const string InvalidAbout =
            @"Lorem ipsum dolor sit amet, vel aliquet fermentum leo per, ut eu justo. Maecenas in, at faucibus, ac volutpat pede, lobortis vel lorem porttitor dolore. Tellus taciti ut vitae, ut ipsum, suspendisse tortor non eleifend, sed adipiscing cras vehicula mollis. Libero maecenas tristique molestie ante elit praesent, sit ante cursus a elementum. Hendrerit in porttitor mauris, wisi rutrum lorem iure mus ultrices, wisi etiam cum neque mollis ipsum. Nisl nonummy sit mauris arcu.
Ac vel urna.Vivamus ut conubia lobortis, sollicitudin autem eleifend dictum conubia ut, elit suspendisse leo potenti eget integer ac, vehicula fusce est, duis vehicula orci at eu ante ac.Sed vitae porta in, donec turpis, et ut curae pellentesque enim sollicitudin.Dolor amet enim placerat suspendisse at, enim malesuada suspendisse commodo nibh, nisl dui vestibulum nulla sit nam, mauris ligula wisi sed quis, et lacinia dignissim ullamcorper semper.Metus dis lobortis purus.Etiam neque ut cursus, neque mauris urna pharetra wisi pede. Pede vehicula vel sodales dolor, ullamcorper dui in justo id et at.
Ante consectetuer at in, sed eros tristique nibh enim mi. In vestibulum eros mauris at, ut congue wisi ornare sagittis orci, nulla excepteur, ullamcorper aliquip id quis ultrices lectus consectetuer.Turpis augue elementum eu luctus nec eget, quis lacus volutpat, euismod diam tellus ac posuere, augue justo sit sed dolor ligula magna.Quisquam faucibus. Tempus cras suspendisse sed, venenatis ut congue tristique ornare wisi bibendum.Lacinia neque vestibulum, sed tincidunt dui leo vehicula, gravida nec massa suscipit pellentesque amet. Justo nec, sodales erat eleifend neque nunc fringilla risus, pellentesque blandit. In vivamus magnis facilisi nec vitae, vel tellus nulla hac a id sed, vestibulum nec accumsan quis posuere justo, quisque iaculis per justo id diam, eleifend dictum.
Egestas dui vehicula vestibulum feugiat sollicitudin tortor, faucibus tortor vestibulum, eget sed lacinia, mi quam tortor tincidunt donec nisl. Magnis ultricies tincidunt fermentum ipsum nibh libero.Rutrum in vel sagittis at condimentum id, erat eu odio interdum, rutrum dictum suspendisse condimentum, aliquam purus vitae cursus, massa dolor justo phasellus. Ut leo, purus ipsum eu augue nec.Pharetra id augue, amet ullam. Velit in in dolor varius urna occaecat, ultrices eget libero mauris mus tellus rhoncus.Lorem mus volutpat, commodo porttitor donec lectus ullamcorper, quis neque urna ipsum vel, egestas faucibus augue tempus magna congue, taciti lacus tempus quis. Congue vel nec suspendisse, at non aliquam, pharetra molestie ipsum nunc, urna sem convallis.";

        public const string ValidAbout =
            @"Lorem ipsum dolor sit amet, vel aliquet fermentum leo per, ut eu justo. Maecenas in, at faucibus, ac volutpat pede, lobortis vel lorem porttitor dolore. Tellus taciti ut vitae, ut ipsum, suspendisse tortor non eleifend, sed adipiscing cras vehicula mollis. Libero maecenas tristique molestie ante elit praesent, sit ante cursus a elementum. Hendrerit in porttitor mauris, wisi rutrum lorem iure mus ultrices, wisi etiam cum neque mollis ipsum. Nisl nonummy sit mauris arcu.";
    }
}